apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cat-app
  template:
    metadata:
      labels:
        app: cat-app
    spec:
      containers:
        - name: app
          image: varkeychanjacob/go-server:amd64  
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cat-app
  labels:
    app: cat-app
spec:
  ports:
    - port: 8087
      name: http
      targetPort: 8080
  selector:
    app: cat-app
  type: LoadBalancer